        <!-- footer -->
        <div class="footer">
            <div class="container">
                <div class="col-md-3 information">
                    <h4>Information</h4>
                    <div class="nav-bottom">
                        <ul>
                            <li><a href="about.html">About</a></li>
                            <li><a href="news.html">News</a></li>
                            <li><a href="events.html">Events</a></li>
                            <li><a href="404.html">Blog</a></li>
                            <li><a href="contact.html">Contacts</a></li>
                            <div class="clearfix"></div>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 keep">
                    <h4>follow us</h4>
                    <div class="social">
                        <ul>
                            <li><a href="#"><i class="facebok"> </i></a></li>
                            <li><a href="#"><i class="twiter"> </i></a></li>
                            <li><a href="#"><i class="rss"> </i></a></li>
                            <div class="clearfix"></div>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 email">
                    <h4>Email updates</h4>
                    <p>Curabitur justo augue, euismod nec tortor tincidunt.</p>
                    <div class="email-top">
                        <form>
                            <input type="text" class="text" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}">
                        </form>
                    </div>
                </div>
                <div class="col-md-3 conta">
                    <h4>Contact us</h4>
                    <p>Tel 1:+1 234 567 8767</p>
                    <p>Tel 2:+1 234 567 8767</p>
                </div>
                <div class="clearfix"> </div>
                <div class="bottom">
                    <p>Copyrights © 2015 Hiking All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
                </div>
            </div>
        </div>
        <!-- footer -->

	</body>
</html>
