        <!-- footer -->
        <div class="footer">
            <div class="container">
                <div class="col-md-3 information">
                    <h4>Information</h4>
                    <div class="nav-bottom">
                        <ul>
                            <li><a href="about.html"><?php echo $lang['MENU_ABOUT']; ?></a></li>
                            <li><a href="news.html"><?php echo $lang['MENU_NEWS']; ?></a></li>
                            <li><a href="events.html"><?php echo $lang['MENU_EVENTS']; ?></a></li>
                            <li><a href="404.html">Blog</a></li>
                            <li><a href="contact.html"><?php echo $lang['MENU_CONTACT']; ?></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 keep">
                    <h4>follow us</h4>
                    <div class="social">
                        <ul>
                            <li><a href="#"><i class="facebok"> </i></a></li>
                            <li><a href="#"><i class="twiter"> </i></a></li>
                            <li><a href="#"><i class="rss"> </i></a></li>
                            <div class="clearfix"></div>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 email">
                    <h4><?php echo $lang['FOOTER_EMAIL_UPDATES']; ?></h4>
                    <p>Curabitur justo augue, euismod nec tortor tincidunt.</p>
                    <div class="email-top">
                        <form>
                            <input type="text" class="text" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}">
                        </form>
                    </div>
                </div>
                <div class="col-md-3 conta">
                    <h4><?php echo $lang['FOOTER_CONTACT_US']; ?></h4>
                    <p>Tel 1:+1 234 567 8767</p>
                    <p>Tel 2:+1 234 567 8767</p>
                </div>
                <div class="clearfix"> </div>
                <div class="bottom">
                    <p>Copyrights © 2015 Hiking All rights reserved</p>
                </div>
            </div>
        </div>
        <!-- footer -->

	</body>
</html>
