        <!-- footer -->
        <div class="footer">
            <div class="container" >
                <div class="col-md-3 information">
                    <h4>Information</h4>
                    <div class="nav-bottom">
                        <ul>
                            <li><a href="<?php echo URL_DIR.'home';?>"><?php echo $lang['MENU_NEWS']; ?></a></li>
                            <li><a href="<?php echo URL_DIR.'tour/hiking';?>"><?php echo $lang['MENU_TOUR']; ?></a></li>
                            <li><a href="<?php echo URL_DIR.'general/about';?>"><?php echo $lang['MENU_ABOUT']; ?></a></li>
                            <li><a href="<?php echo URL_DIR.'general/contact';?>"><?php echo $lang['MENU_CONTACT']; ?></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 keep"style="padding-left: 10%">
                    <h4>follow us</h4>
                    <div class="social">
                        <ul>
                            <li><a href="#"><i class="facebok"> </i></a></li>
                            <li><a href="#"><i class="twiter"> </i></a></li>
                            <li><a href="#"><i class="rss"> </i></a></li>
                            <div class="clearfix"></div>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 conta" style="padding-left: 13%">
                    <h4><?php echo $lang['FOOTER_CONTACT_US']; ?></h4>
                    <p>Tel. +41 (0)27 / 327 35 80</p>

                </div>
                <div class="clearfix"> </div>

            </div>
        </div>
        <!-- footer -->

	</body>
</html>
